query {
  ads(orderBy: { column: CREATED_AT, order: DESC }, trashed: ONLY) {
    data {
      id
      title
      description
      price
      sku
      negotiable
      created_at
      taxonomyContents {
        data {
          id

          title
        }
      }
      user {
        id
        name
        country {
          id

          code
          name
          phone_code
        }
        state {
          id
          name
        }
      }
    }
  }
}
